# number of replicas to run
replicaCount: 1

# number of helm release revisions to retain
revisionHistoryLimit: 5

# Default internal between alert checks against the elasticsearch datasource, in minutes
runIntervalMins: 1

# Default rule buffer duration, in minutes
bufferTimeMins: 15

# Amount of time to retry and deliver failed alerts (1440 minutes per day)
alertRetryLimitMins: 2880

# Default time before realerting, in minutes
realertIntervalMins: ""

writebackIndex: elastalert

image:
  # docker image
  repository: jertel/elastalert-docker
  # docker image tag
  tag: 0.2.1
  pullPolicy: IfNotPresent
resources: {}

elasticsearch:
  # elasticsearch endpoint e.g. (svc.namespace||svc)
  host: "elasticsearch-master"
  # elasticsearch port
  port: 9200
  # whether or not to connect to es_host using TLS
  useSsl: "False"
  # Username if authenticating to ES with basic auth
  username: ""
  # Password if authenticating to ES with basic auth
  password: ""
  # whether or not to verify TLS certificates
  verifyCerts: "True"
  # Enable certificate based authentication
  # path to a PEM certificate to use as the client certificate
  # clientCert: "/certs/client.pem"
  # path to a private key file to use as the client key
  # clientKey: "/certs/client-key.pem"
  # path to a CA cert bundle to use to verify SSL connections
  # caCerts: "/certs/ca.pem"
  # # certs volumes, required to mount ssl certificates when elasticsearch has tls enabled
  # certsVolumes:
  #   - name: es-certs
  #     secret:
  #       defaultMode: 420
  #       secretName: es-certs
  # # mount certs volumes, required to mount ssl certificates when elasticsearch has tls enabled
  # certsVolumeMounts:
  #   - name: es-certs
  #     mountPath: /certs
  #     readOnly: true

extraConfigOptions: 
  smtp_host: smtp.sendgrid.net
  smtp_port: 587
  smtp_auth_file: /opt/config-smtp/smtp-auth.yaml
  from_addr: elastalert@domain.com
  notify_email: someone@domain.com

  # # Options to propagate to all rules, e.g. a common slack_webhook_url or kibana_url
  # # Please note at the time of implementing this value, it will not work for required_locals
  # # Which MUST be set at the rule level, these are: ['alert', 'type', 'name', 'index']
  # generate_kibana_link: true
  # kibana_url: https://kibana.yourdomain.com
  # slack_webhook_url: dummy

# rule configurations e.g. (http://elastalert.readthedocs.io/en/latest/)

rules:
  bad_output: |-
    name: Bad output
    type: any
    index: filebeat-*
    filter:
    - query:
        query_string:
          query: "message: bad OR message: worse"
    alert:
    - "email"
    realert: 
      minutes: 10
    exponential_realert:
      hours: 1
    email:
    - "someone@domain.com"  

# Support using node selectors and tolerations
# nodeSelector:
#   "node-role.kubernetes.io/infra_worker": "true"
nodeSelector: {}
# tolerations:
#   - key: "node_role"
#     operator: "Equal"
#     value: "infra_worker"
#     effect: "NoSchedule"
tolerations: 

extraVolumes: 
 - name: smtp-auth
   secret:
     secretName: elastalert-smtp-auth
     items:
       - key: smtp-auth.yaml
         path: smtp-auth.yaml
         mode: 0400

extraVolumeMounts: 
 - name: smtp-auth
   mountPath: /opt/config-smtp/smtp-auth.yaml
   subPath: smtp-auth.yaml
   readOnly: true
